spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/spzx-cloud-user?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
  rabbitmq:
    username: guest
    password: admin
    host: 192.168.188.100
    port: 5672
    publisher-returns: true
  redis:
    host: 192.168.188.100
    database: 0
    port: 6379
  cache:
    cache-names: menus_cache
server:
  port: 8081
  compression:
    enabled: true
fastdfs:
  nginx:
    host: http://192.168.91.128/
logging:
  level:
    com.vhr: debug